name: release-smart-adder

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches: master

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config gh

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Prepare release
        run: |
          cargo install cargo-smart-release
          cargo login "$CARGO_REGISTRY_TOKEN"

      - name: Dry run publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATE_SMART_ADDER }}
        shell: bash
        run: |
          cargo smart-release --update-crates-index --dry-run-cargo-publish smart-adder

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATE_SMART_ADDER }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cargo smart-release --update-crates-index --execute smart-adder
