name: Release smart-add-one-new crate

on:
  workflow_dispatch:
    inputs:
      version:
        description: "major/minor/patch or semver"
        required: false
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Login to crates.io
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          command: login
          args: ${{ secrets.CARGO_REGISTRY_TOKEN_SMART_ADD_ONE_NEW }}

      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish crate
        uses: kaleidawave/crates-release-gh-action@main
        id: release
        with:
          version: ${{ github.event.inputs.version }}
          crates-token: ${{ secrets.CARGO_REGISTRY_TOKEN_SMART_ADD_ONE_NEW }}
          working-directory: add_one

      - name: Push updated Cargo.toml
        run: |
          git tag "v${{ steps.release.outputs.new-version }}"
          git add .
          git commit -m "Release: ${{ steps.release.outputs.new-version }}"
          git push --tags origin master
